-
  title: Simple build
  build: true
-
  title: Compare build
  compare: _expected/site _site
-
  title: Should build with separate javascript and stylesheet files
  build: true
  config:
    octopress: _combine_false.yml
  compare:
    - _expected/combine_css_false _site/stylesheets
    - _expected/combine_js_false _site/javascripts
-
  title: Should compress stylesheets and javascripts
  build: true
  config:
    octopress: _compress_false.yml
  compare:
    - _expected/compress_false/stylesheets _site/stylesheets
    - _expected/compress_false/javascripts _site/javascripts
-
  title: Should copy all theme assets
  before: octopress ink copy theme --path _copy --force
  compare: _expected/copy_test _copy
  after: rm -rf _copy
-
  title: Should copy only pages and layouts
  before: octopress ink copy theme --layouts --pages --path _copy --force
  compare: _expected/copy_layouts_pages _copy
  after: rm -rf _copy
-
  title: Should create a plugins scaffold
  before: 
    - 'git config user.name > .git-config-user-name'
    - 'git config user.email > .git-config-user-email'
    - 'git config user.name ""'
    - 'git config user.email ""'
    - 'octopress ink new test-theme --theme'
    - 'rm -rf test-theme/.git'
  compare: _expected/test-theme-expected test-theme
  after:
    - 'cat .git-config-user-name | tr -d "\n" | xargs -0 git config user.name'
    - 'cat .git-config-user-email | tr -d "\n" | xargs -0 git config user.email'
    - 'rm -rf test-theme .git-config-user-name .git-config-user-email'
